encoding: utf-8
exclude: [vendor]
gh_pages_url_prefix: https://github.com/psicotron3/BlueRetroWebCfg
gh_url_prefix: https://github.com/psicotron3/BlueRetroWebCfg/blob/master
google_analytics: G-N87L56T313
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
  - package.json
  - README.md
  - node_modules
  - Gemfile
  - vendor
